<?php
//--- This code is generated by ProBot ---
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Sobok;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class SobokController extends Controller{

	public function index(){
		$soboks=Sobok::paginate(10);
		return view("pages.erp.sobok.index_sobok",["soboks"=>$soboks]);
	}
	public function create(){

		return view("pages.erp.sobok.create_sobok",[]);
	}
	public function store(Request $request){
//		Sobok::create($request->all());
		$sobok=new Sobok;
		$sobok->name=$request->txtName;
		$sobok->deleted_at=$request->txtDeleted_at;

		$sobok->save();
		return back()->with('success','Created Successfully.');
  
	}

	public function update(Request $request){
//		$sobok->update($request->all());

        $sobokid=$request->input('cmbsobokId');

		$sobok = Sobok::find($sobokid);
		$sobok->id=$request->cmbsobokId;
		$sobok->name=$request->txtName;
		$sobok->deleted_at=$request->txtDeleted_at;

		$sobok->update();
		return redirect()->route("soboks.index")->with('success','Updated Successfully.');
    
	}
	public function show($id){
		$ssobok=Sobok::find($id);
		return response()->json([
			'status'=>200,
			'ssobok'=>$ssobok
		]);
	}
	public function edit($id){
		$sobok=Sobok::find($id);
		return response()->json([
			'status'=>200,
			'sobok'=>$sobok
		]);
	}

	public function destroy(Request $request){
		
		$sobokid=$request->input('d_sobok');
		$sobok= Sobok::find($sobokid);
		$sobok->delete();


		return redirect()->back()
			   ->with('success',' Deleted successfully');
	}
}
